services:
  api:
    container_name: dami-api
    hostname: dami
    depends_on:
      - database
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: sh -c "./dami-api"
    volumes:
      - api:/dami/certs
  database:
    container_name: dami-db
    hostname: database
    image: mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      #Ao criar um MYSQL_USER, MYSQL_PASSWORD e MYSQL_DATABASE, o contêiner do MySQL cria o banco,
      #seta a senha pra logar com root, cria o usuário com a senha definida e dá a ele todas as permissões necessárias no banco especificado
      MYSQL_USER: dami
      MYSQL_PASSWORD: damitest
      MYSQL_ROOT_PASSWORD: brunorubro
      MYSQL_DATABASE: dami

volumes:
  api:
  db:
