name: Deploy para o server
run-name: Aplicando ${{ github.ref_name }} na main e fazendo o deploy em produção
on:
  push:
    branches:
      - main

jobs:
  update-api:
    needs: test-code
    name: Atualizar API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/dami/napi
            git pull
            systemctl restart api
          script_stop: true